const listOfRegistrationRequests = [
  {
    fname: "Chuck",
    companyName: "Plus Petroleum Limited",
    lname: "Nwapa",
    phone: "+2348100023097",
    email: "cen@plus-petro.com",
    approved: true,
    used: 1583740771683,
  },
  {
    fname: "Johnson",
    companyName: "MITYLENE ENERGY NIGERIA LIMITED",
    lname: "Morgan",
    phone: "08030717942",
    email: "info.mitylene@gmail.com",
    approved: true,
  },
  {
    fname: "HARRISON",
    companyName: "HOMIK ENGINEERING LIMITED",
    approved: true,
    lname: "UYO",
    phone: "+2347056035020",
    email: "uyo.harrison@homikengineeringltd.com",
  },
  {
    fname: "SOLOMON",
    companyName: "S.G.HARRY (NIG.) ENT. ",
    approved: true,
    lname: "HARRY",
    phone: "+2348030947966",
    email: "alphadelconsultltd@yahoo.com",
  },
  {
    fname: "Shona ",
    companyName: "Rotawn Energy and Logistics Services Limited",
    lname: "Prest ",
    phone: "+2349030001799",
    email: "shona.prest@gmail.com",
    approved: true,
  },
  {
    fname: "Awajikerem",
    companyName: "Arrow Construction Company Limited",
    lname: "ALABO",
    phone: "+2348034794470",
    email: "esuikup.kerem@arrowconn.com",
    approved: true,
    used: 1589368801052,
  },
  {
    fname: "Ifeoma",
    companyName: "Caverton Helicopters",
    lname: "Okoro",
    phone: "+2348168963972",
    email: "ifeoma.okoro@caverton-helicopters.com",
    approved: true,
    used: 1583224771136,
  },
  {
    fname: "TINA",
    companyName: "TITAN PROJECTS NIGERIA LIMITED",
    lname: "OHALE",
    phone: "+2348060966354",
    email: "tina.ohale@titanprojectsng.com",
    approved: true,
    used: 1582716478540,
  },
  {
    fname: "chiamaka",
    companyName: "AOS ORWELL",
    lname: "ezeonwuka",
    phone: "+2348028596414",
    email: "chidinma_e2003@yahoo.co.uk",
    approved: true,
  },
  {
    fname: "Santosh",
    companyName: "Hydrocarbon Support Concepts Limited",
    lname: "Ramavarma",
    phone: "+2348037893679",
    email: "santosh@hydrocarbon.ng",
    approved: true,
    used: 1583166751336,
  },
  {
    fname: "OLUWAFEMI",
    companyName: "GREENSVILLE ROPES AND ACCESSORIES LIMITED",
    approved: true,
    lname: "OWOSENI",
    phone: "+2348055111561",
    email: "greensvilleropes@gmail.com",
  },
  {
    fname: "Albert ",
    companyName: "Raloson Global Nigeria Ltd",
    approved: true,
    lname: "Ogwunte ",
    phone: "+2347082405792",
    email: "ral_oson@yahoo.co.uk",
  },
  {
    fname: "Kunle",
    companyName: "Petrogap Oil and Gas Limited",
    lname: "Akeju",
    phone: "+2348033066084",
    email: "info@petrogap.com",
    approved: true,
    used: 1586436790386,
  },
  {
    fname: "Ehis",
    companyName: "Project Masters Nig. Ltd.",
    lname: "Onobun",
    phone: "+2348033408993",
    email: "ehis.onobun@projectmastersng.com",
    approved: true,
  },
  {
    fname: "CHISOM",
    companyName: "FIRST PRIORITY RESOURCES INTERNATIONAL LIMITED",
    lname: "OBIKILE",
    phone: "+2349028878176",
    email: "uche@firstpriorityltd.com",
    approved: true,
    used: 1582284728231,
  },
  {
    fname: "Raphael",
    companyName: "Seal Energy and Investment Company Ltd",
    lname: "Adaka",
    phone: "+2348133222254",
    email: "info@seal-energy.com",
    approved: true,
    used: 1584712895783,
  },
  {
    fname: "NDUBUISI",
    companyName: "ENJ PROJECTS NIGERIA LIMITED",
    lname: "OBIENU",
    phone: "+2348067807276",
    email: "enj.projects@yahoo.com",
    approved: true,
  },
  {
    fname: "Ramesh ",
    companyName: "EUNISELL LIMITED",
    lname: "Hullur",
    phone: "+234903356575",
    email: "ramesh.hullur@eunisell.com",
    approved: true,
  },
  {
    fname: "Benson",
    companyName: "FRAMAK ENERGY SERVICES LIMITED",
    lname: "Ikechukwu",
    phone: "+2348055495904",
    email: "framakenergyserv@gmail.com",
    approved: true,
    used: 1587645954138,
  },
  {
    fname: "Bosede",
    companyName: "LUBEN EDGE LIMITED",
    approved: true,
    lname: "Allen-Taylor",
    phone: "+2348023301956",
    email: "boslentor@gmail.com",
  },
  {
    fname: "JENNIFER",
    companyName: "EMCO OILFIELD SERVICES LIMITED",
    lname: "OKEREKE",
    phone: "+2348034751726",
    email: "okerekej@emcoservices.com",
    approved: true,
    used: 1601394457163,
  },
  {
    fname: "Seun",
    companyName: "Test Company - Kay Company LTD",
    lname: "Kay",
    phone: "+234892020220",
    email: "kay@kay.com",
    approved: true,
  },
  {
    fname: "DR. EMI",
    companyName: "ELSHCON NIGERIA LIMITED",
    approved: true,
    lname: "MEMBERE-OTAJI",
    phone: "+2348033107554",
    email: "info@elshcon.com",
  },
  {
    fname: "Godstime",
    companyName: "G.T.P Global Resources Nigeria Limited ",
    lname: "Okene",
    phone: "+2340803670596",
    email: "godstime.okene@gtpng.com",
    approved: true,
    used: 1583139763600,
  },
  {
    fname: "Imma",
    companyName: "RiverSafe Solutions Nig. Ltd",
    lname: "Chika",
    phone: "+2348033387959",
    email: "secretary@riversafe-ng.com",
    approved: true,
    used: 1582882633709,
  },
  {
    fname: "YVES",
    companyName: "DIACREST INT'L LIMITED",
    lname: "OKPURE",
    phone: "+2348056219606",
    email: "yokpure@diacrestgroup.com",
    approved: true,
    used: 1582642072032,
  },
  {
    fname: "Ifeyinwa",
    companyName: "ifeyinwa.jim@rotawn.com",
    lname: "Jim",
    phone: "+2348130452301",
    email: "ifeyinwa.jim@rotawn.com",
    approved: true,
  },
  {
    fname: "Tony",
    companyName: "Nestoil Ltd",
    approved: true,
    lname: "Adano",
    phone: "+2347069549917",
    email: "t.adano@nestoilgroup.com",
  },
  {
    fname: "Edith",
    companyName: "Librod Energy Services Limited",
    lname: "Ukah",
    phone: "+2348176665010",
    email: "edith.ukah@librod.com",
    approved: true,
    used: 1590744713312,
  },
  {
    fname: "Brown",
    companyName: "IFAJOSCO INTEGRATED SERVICES LIMITED",
    lname: "Ibokene",
    phone: "+2348068002730",
    email: "ibokenebrown@gmail.com",
    approved: true,
  },
  {
    fname: "Test",
    companyName: "Test Company Limited",
    lname: "Tester",
    phone: "+23489922000",
    email: "tester@test.com",
  },
  {
    fname: "ANTHONY",
    companyName: "TPAUL INTEGRATED SERVICES LIMITED",
    approved: true,
    lname: "USONGO",
    phone: "07010471197",
    email: "info@tpaulintegrated.com",
  },
  {
    fname: "Helen",
    companyName: "Lonadek Inc.",
    lname: "Ezeh",
    phone: "+2348033216064",
    email: "secretariat@lonadek.com",
    approved: true,
    used: 1588705824310,
  },
  {
    fname: "Akinmuda",
    companyName: "VURIN LIMITED",
    lname: "Omoseyin",
    phone: "+2349087191495",
    email: "info@vuringroup.com",
    approved: true,
    used: 1585035943296,
  },
  {
    fname: "Mel",
    companyName: "Test Company 2",
    lname: "Moore",
    phone: "+234123456780",
    email: "melsmore.mouse@outlook.com",
    approved: true,
  },
  {
    fname: "CHISOM",
    companyName: "FIRST PRIORITY RESOURCES INTERNATIONAL LIMITED",
    approved: true,
    lname: "OBIKILE",
    phone: "+2349028878176",
    email: "chisom@firstpriorityltd.com",
  },
  {
    fname: "Femi",
    companyName: "AOS Orwell Limited",
    lname: "Omotayo",
    phone: "+2349055034044",
    email: "marketing@aosorwell.com",
    approved: true,
  },
  {
    fname: "ETIENAM",
    companyName: "INT'L ENERGY SERVICES LIMITED",
    lname: "ARIT",
    phone: "+2348181534439",
    email: "etienam.a@ieslglobal.com",
    approved: true,
  },
  {
    fname: "Deborah",
    companyName: "Telmek Global Resources Limited",
    approved: true,
    lname: "Nwanoka",
    phone: "+2349090071762",
    email: "b.nwanoka@telmekglobal.com",
  },
  {
    fname: "Horace",
    companyName: "BRADE ",
    lname: "Enemugwem",
    phone: "+2348102373753",
    email: "henemugwem@bradeafrica.com",
    approved: true,
  },
  {
    fname: "Kazeem",
    companyName: "Liliady Marine and Energy Services Limited",
    lname: "Shittu",
    phone: "+2348028148804",
    email: "info@liliady-marine.com",
    approved: true,
    used: 1584449776639,
  },
  {
    fname: "GRACE",
    companyName: "PEGIS GLOBAL SERVICES LIMITED ",
    approved: true,
    lname: "UYANWANNE",
    phone: "+2347062324870",
    email: "businessdevelopment@pegisglobal.com",
  },
  {
    fname: "TUNDE",
    companyName: "DOVEWELL OILFIELD SERVICES LIMITED",
    lname: "AJALA",
    phone: "+2348032413664",
    email: "tunde.ajala@dovewellgroup.com",
    approved: true,
  },
  {
    fname: "Chiamaka",
    companyName: "AOS ORWELL",
    lname: "Ezeonwuka",
    phone: "+2348028596414",
    email: "chiamaka.ezeonwuka@aosorwell.com",
    approved: true,
  },
  {
    fname: "Oti",
    companyName: "Oiltest Services Limited",
    lname: "Oteri",
    phone: "+2347064277167",
    email: "contractsupport@oiltestgroup.com",
    approved: true,
    used: 1583839981906,
  },
  {
    fname: "Derin",
    companyName: "Beniko Industries Ltd",
    approved: true,
    lname: "ADEYI",
    phone: "derin@beniko.co",
    email: "sales@beniko.com",
  },
  {
    fname: "Solomon",
    companyName: "AETOS LIMITED",
    lname: "Oguh",
    phone: "+2348056145561",
    email: "sales@aetosng.com",
    approved: true,
  },
  {
    fname: "CHIMEZIE",
    companyName: "SYNERGY ENVIRONMENT EXPERT GLOBAL LIMITED",
    approved: true,
    lname: "NWOGU",
    phone: "+2348033090166",
    email: "synergyglobalexpert2009@gmail.com",
  },
  {
    fname: "Horsfall ",
    companyName: "Chesroc Nigeria Limited",
    approved: true,
    lname: "Joshua",
    phone: "+2348090363170",
    email: "jhorsfall@chesroc.com",
  },
  {
    fname: "ESE",
    companyName: "ALVIN SERVICES LIMITED",
    lname: "AGWI",
    phone: "+2348023250340",
    email: "alvinserv@yahoo.com",
    approved: true,
  },
  {
    fname: "Abhulimen",
    companyName: "New Energy Services Company Limited",
    approved: true,
    lname: "Imafidon",
    phone: "014547908",
    email: "info@nesscong.org",
  },
  {
    fname: "SHARON",
    companyName: "ATMA GLOBAL RESOURCES LIMITED",
    lname: "GODWIN",
    phone: "+2340906862009",
    email: "info@atmaglobalng.com",
    approved: true,
  },
  {
    fname: "Lawal",
    companyName: "DFCI LIMITED",
    lname: "Abdulmumin",
    phone: "+2348086646000",
    email: "lawal_mumin@dfci.com.ng",
    approved: true,
    used: 1583485795969,
  },
  {
    fname: "Gbolahan",
    companyName: "GIL AUTOMATIONS LIMITED",
    approved: true,
    lname: "Lawal",
    phone: "+2348093930328",
    email: "sales@gilautomation.com",
  },
  {
    fname: "OMOTAYO",
    companyName: "WELLQUIP ENERGY SERVICES LIMITED ",
    lname: "BABATOPE",
    phone: "+2348036682386",
    email: "info@wellquipenergy.com",
    approved: true,
    used: 1582541193171,
  },
  {
    fname: "Chinwe",
    companyName: "HABRAMS ENERGY",
    lname: "Ofulue",
    phone: "+2348056970317",
    email: "chinwe.ofulue@habrams.com",
    approved: true,
    used: 1589304903655,
  },
  {
    fname: "Pius",
    companyName: "United vanguard insurance broker",
    approved: true,
    lname: "Uloko",
    phone: "+2348023604605",
    email: "ulokop2002@yahoo.co.uk",
  },
  {
    fname: "Ugwuanyi ",
    companyName: "Chibeco Oil and Gas Nigeria Limited",
    lname: "Julius Chikaodili",
    phone: "+2348033418931",
    email: "offshore-onshore@chibecooilandgasnigltd.org",
    approved: true,
  },
  {
    fname: "Chioma",
    companyName: "OMSA",
    lname: "Okonkwo",
    phone: "+2348038114682",
    email: "bunkers@omsaservices.com",
    approved: true,
    used: 1583485558338,
  },
  {
    fname: "jonathan",
    companyName: "skids logistics ltd",
    approved: true,
    lname: "ataisi",
    phone: "+2348035529398",
    email: "jonathan.ataisi@skidslogistics.com",
  },
  {
    fname: "NDUBUISI",
    companyName: "ENJ PROJECTS NIGERIA LIMITED",
    lname: "OBIENU",
    phone: "+2348067807276",
    email: "info@enjprojects.com",
    approved: true,
  },
  {
    fname: "Robert",
    companyName: "Proserv Instrumentation Nigeria Ltd",
    lname: "Coker",
    phone: "2348037110736",
    email: "robert.coker@proserv.com.ng",
    approved: true,
    used: 1587658364916,
  },
  {
    fname: "Matthew",
    companyName: "Blueveld Nigeria Limited",
    lname: "Akoni",
    phone: "+23408037768111",
    email: "blueveldndt@yahoo.com",
    approved: true,
    used: 1582903457778,
  },
  {
    fname: "HENRY",
    companyName: "ENERGY AFRIC DEVELOPERS INT'L LIMITED",
    lname: "MACAULEY",
    phone: "+23490790204098",
    email: "hmj@energyafric.com",
    approved: true,
    used: 1582550824539,
  },
  {
    fname: "Bukunola",
    companyName: "11 PLC",
    lname: "Ajayi",
    phone: "+2348035330000",
    email: "bukunola.o.ajayi@11plc.com",
    approved: true,
    used: 1586883176170,
  },
  {
    fname: "FRANCIS",
    companyName: "COMPRESSION AND POWER SYSTEMS LIMITED",
    lname: "TUEDOR",
    phone: "+2340809283560",
    email: "info@cpslgroup.com",
    approved: true,
    used: 1583407568717,
  },
  {
    fname: "Arulnithi",
    companyName: "MFI Office Solutions Africa Limited",
    lname: "Thiyagarajan",
    phone: "+2348128600163",
    email: "a.nithi@groupmfi.com",
    approved: true,
    used: 1589362174369,
  },
  {
    fname: "Peter",
    companyName: "Perotex Integrated Services Limited",
    approved: true,
    lname: "Ekanem",
    phone: "+2348035027583",
    email: "perotexbiz@yahoo.com",
  },
  {
    fname: "Chibor",
    companyName: "Amvile Services Company Limited",
    approved: true,
    lname: "Joy",
    phone: "+2340814232145",
    email: "a.joy@amvileservices.com",
  },
  {
    fname: "Bunmi ",
    companyName: "Brone Positioning and Survey Limited",
    lname: "Akomolede",
    phone: "+2348033416763",
    email: "bako@brone-survey.com",
    approved: true,
    used: 1583248006106,
  },
  {
    fname: "Adesegun",
    companyName: "Silverflakes Ltd",
    lname: "Adejare",
    phone: "+23409097438431",
    email: "silverflakes.ltd@aol.com",
    approved: true,
    used: 1582903686015,
  },
  {
    fname: "Pamela",
    companyName: "Rit-Beulah Engineering Services",
    approved: true,
    lname: "Nwabara",
    phone: "+2348063591032",
    email: "info@rit-bengineering.com",
  },
  {
    fname: "Tamunokuro ",
    companyName: "Pogs and Mayer limited",
    approved: true,
    lname: "Douglas",
    phone: "+2348120029296",
    email: "tammyisodouglas@yahoo.com",
  },
  {
    fname: "Dave",
    companyName: "Royal India Company",
    lname: "Kay",
    phone: "+23424652855",
    email: "kay@yahoo.com",
    approved: true,
    used: 1582214840724,
  },
  {
    fname: "AKINWALE",
    companyName: "GENNESARET RESOURCES NIGERIA LIMITED",
    lname: "ESO",
    phone: "+2348034012002",
    email: "info@gennesaretresources.com",
    approved: true,
    used: 1582584267804,
  },
  {
    fname: "Wellshare",
    companyName: "Wellshare Imperial",
    lname: "Imperial",
    phone: "+2348121785333",
    email: "wellshareimperial@gmail.com",
    approved: true,
  },
  {
    fname: "Steve",
    companyName: "Elfren Integrated Ltd",
    lname: "Oyene",
    phone: "+2348092220385",
    email: "info@elfrenltd.com",
    approved: true,
  },
  {
    fname: "Ifeyinwa",
    companyName: "Rotawn Energy & Logistics Ltd",
    lname: "Jim",
    phone: "+2347046395752",
    email: "info@rotawn.com",
    approved: true,
  },
  {
    fname: "Chinwe",
    companyName: "AB OFFSHORE MARINE SERVICES LIMITED",
    approved: true,
    lname: "Okuteze",
    phone: "+23407054493036",
    email: "business@aboffshore.ng",
  },
  {
    fname: "JOEL",
    companyName: "STANDARD MANAGERS LIMITED",
    lname: "JOEL",
    phone: "+2348033020505",
    email: "joel@standardmanagers.com",
    approved: true,
    used: 1582305658004,
  },
  {
    fname: "Tarebi",
    companyName: "Yoke Solutions Limited",
    lname: "Alebiosu",
    phone: "+2347061240799",
    email: "tarebi@yokesolutions.com",
    approved: true,
  },
  {
    fname: "Terry",
    companyName: "Duncan Maritime Ventures Limited ",
    lname: "Ayamre",
    phone: "+2348094222224",
    email: "terrya@duncanmaritime.com",
    approved: true,
    used: 1587642561734,
  },
  {
    fname: "Ignatius",
    companyName: "Routhian Loci Services Ltd",
    approved: true,
    lname: "Naade",
    phone: "+2347088358583",
    email: "routhian.loci@gmail.com",
  },
  {
    fname: "Joy",
    companyName: "IHRDC ",
    approved: true,
    lname: "Nwokocha",
    phone: "+2348034922247",
    email: "jnwokocha@ihrdc.com",
  },
  {
    fname: "Joseph",
    companyName: "LO-MICHAELS INTERNATIONAL LIMITED",
    lname: "Ezarevah",
    phone: "+2348065716400",
    email: "lomicheals67@gmail.com",
    approved: true,
    used: 1588420778776,
  },
  {
    fname: "INYENE",
    companyName: "KNOTS & GEAR",
    lname: "BENSON",
    phone: "+2348035907230",
    email: "ibenson@knotsandgear.com",
    approved: true,
    used: 1582714891702,
  },
  {
    fname: "Femi",
    companyName: "Tropical Artic Logistics Ltd (TAL)",
    lname: "Adeniji",
    phone: "+23407054569234",
    email: "femi@tropicalarcticlogisticsltd.com",
    approved: true,
  },
  {
    fname: "Linda",
    companyName: "JAGAL ENERGY",
    lname: "Egbeocha",
    phone: "+2347036575026",
    email: "linda.egbeocha@jagal.com",
    approved: true,
    used: 1582722451674,
  },
  {
    fname: "Rodolph ",
    companyName: "Builders Resources",
    lname: "Akkary",
    phone: "+2340812222212",
    email: "rodolph@builders-resources.com",
    approved: true,
    used: 1583412586725,
  },
  {
    fname: "Efetobore",
    companyName: "Bristow Helicopters (Nig) LTD",
    lname: "Omene",
    phone: "+2348056798037",
    email: "efetobore.omene@bristowgroup.com",
    approved: true,
    used: 1583416137768,
  },
  {
    fname: "Jerry ",
    companyName: "BORAX ENERGY SERVICES LTD ",
    lname: "Mbanaso ",
    phone: "+2348071418484",
    email: "services@boraxenergyservices.com",
    approved: true,
  },
  {
    fname: "DIKKO",
    companyName: "NEOLEUM ENERGY",
    lname: "ATANU",
    phone: "+2348169991111",
    email: "da@neoleum.com",
    approved: true,
    used: 1582562595941,
  },
  {
    fname: "Gladys",
    companyName: "BellPoint Energy Limited",
    approved: true,
    lname: "Amaefule",
    phone: "+2348058900088",
    email: "gladys@bellpoint.com.ng",
  },
  {
    fname: "Umarani",
    companyName: "Montego Holdings",
    lname: "Opusunju",
    phone: "+2348187215524",
    email: "info@montego.com",
    approved: true,
    used: 1583496304771,
  },
  {
    fname: "Rasheed",
    companyName: "Airmarine Logistics",
    lname: "Bakare",
    phone: "+2347039444888",
    email: "info@airmarineng.com",
    approved: true,
  },
  {
    fname: "Hameed",
    companyName: "Busicon Nigeria Limited",
    lname: "Ogbara",
    phone: "+23408023887798",
    email: "hameed.ogbara@busicongroup.com",
    approved: true,
    used: 1582987055954,
  },
  {
    fname: "Inyang",
    companyName: "Dajim International Company LTD",
    lname: "Ibanga",
    phone: "+2347030173612",
    email: "www.dajiminternational@gmail.com",
    approved: true,
  },
  {
    fname: "SOLOMON",
    companyName: "S.G. HARRY (NIG) ENT.",
    approved: true,
    lname: "HARRY",
    phone: "+2348030947966",
    email: "solo4harry@gmail.com",
  },
  {
    fname: "Obinna",
    companyName: "Cameron Flow Control Technology Nigeria Limited",
    lname: "Nwokoro",
    phone: "+23408034328707",
    email: "onwokoro@cameron.slb.com",
    approved: true,
    used: 1583397333101,
  },
  {
    fname: "PHILIP ",
    companyName: "LONDON OFFSHORE CONSULTANTS NIGERIA LTD",
    lname: "ATITEBI",
    phone: "+2340816357607",
    email: "p.atitebi@loc-group.com",
    approved: true,
    used: 1583405862106,
  },
  {
    fname: "Promise",
    companyName: "Crossfield Engineering & Energy Services Ltd",
    approved: true,
    lname: "Chuku",
    phone: "+2348183040074",
    email: "welleum.info@gmail.com",
  },
  {
    fname: "Chisom",
    companyName: "Calaya Engineering Services Limited",
    approved: true,
    lname: "Anyiam",
    phone: "+2349038536989",
    email: "chisom.anyiam@calayaengineering.com",
  },
  {
    fname: "h.onyeka@fugro.com",
    companyName: "h.onyeka@fugro.com",
    lname: "h.onyeka@fugro.com",
    phone: "h.onyeka@fugro.com",
    email: "h.onyeka@fugro.com",
    approved: true,
    used: 1582268473372,
  },
];

module.exports = {
    listOfRegistrationRequests
}